# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-21 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='gallery.tags'),
        ),
    ]
