# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-21 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_editor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='this is cool', upload_to=''),
        ),
    ]
