# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-25 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20200521_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=90),
        ),
    ]
